-- ==============================
-- DROP OBJECTS (Se existirem)
-- ==============================

-- Dropar triggers
DROP TRIGGER TRG_ITENS_PEDIDO_BI;
DROP TRIGGER TRG_PEDIDO_BI;
DROP TRIGGER TRG_PRODUTO_BI;
DROP TRIGGER TRG_CLIENTE_BI;

-- Dropar tabelas
DROP TABLE ITENS_PEDIDO;
DROP TABLE PEDIDO;
DROP TABLE PRODUTO;
DROP TABLE CLIENTE;

-- Dropar generators
DROP GENERATOR GEN_CLIENTE_ID;
DROP GENERATOR GEN_PRODUTO_ID;
DROP GENERATOR GEN_PEDIDO_ID;

-- ==============================
-- CREATE GENERATORS
-- ==============================

CREATE GENERATOR GEN_CLIENTE_ID;
CREATE GENERATOR GEN_PRODUTO_ID;
CREATE GENERATOR GEN_PEDIDO_ID;

-- ==============================
-- TABELA CLIENTE
-- ==============================

CREATE TABLE CLIENTE (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	NOME VARCHAR(100),
	CEP VARCHAR(8),
	LOGRADOURO VARCHAR(100),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(50),
	UF CHAR(2),
	CODIGO_IBGE VARCHAR(10)
);

-- Trigger para CLIENTE
create TRIGGER TGR_CLIENTE_BI FOR CLIENTE
Before Insert POSITION 0
AS
BEGIN
	IF (NEW.CODIGO IS NULL) THEN
		NEW.CODIGO = GEN_ID(GEN_CLIENTE_ID, 1);
END

-- ==============================
-- TABELA PRODUTO
-- ==============================

CREATE TABLE PRODUTO (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(100),
	VALOR_UNITARIO DECIMAL(15,2)
);

-- Trigger para PRODUTO
create TRIGGER TRG_PRODUTO_BI FOR PRODUTO
Before Insert POSITION 0
AS
BEGIN
     IF (NEW.CODIGO IS NULL) THEN
		NEW.CODIGO = GEN_ID(GEN_PRODUTO_ID, 1);
END;

-- ==============================
-- TABELA PEDIDO
-- ==============================

CREATE TABLE PEDIDO (
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	REFERENCIA VARCHAR(50),
	NUMERO_PEDIDO VARCHAR(20),
	DATA_EMISSAO DATE,
	CODIGO_CLIENTE INTEGER,
	TIPO_OPERACAO VARCHAR(10), -- Entrada/Saída
	TOTAL_PEDIDO DECIMAL(15,2),
	FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO)
);

-- Trigger para PEDIDO
create TRIGGER TRG_PEDIDO_BI FOR PEDIDO
Before Insert POSITION 0
AS
BEGIN
     IF (NEW.CODIGO IS NULL) THEN
		NEW.CODIGO = GEN_ID(GEN_PEDIDO_ID, 1);
END;

-- ==============================
-- TABELA ITENS_PEDIDO
-- ==============================

CREATE TABLE ITENS_PEDIDO (
	CODIGO INTEGER NOT NULL,
	CODIGO_PEDIDO INTEGER NOT NULL,
	CODIGO_PRODUTO INTEGER,
	QUANTIDADE INTEGER,
	VALOR_UNITARIO DECIMAL(15,2),
	TOTAL_ITEM DECIMAL(15,2),
	PRIMARY KEY (CODIGO_PEDIDO, CODIGO),
	FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO),
	FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO)
);

-- Trigger para ITENS_PEDIDO
create TRIGGER TRG_ITENS_PEDIDO_BI FOR ITENS_PEDIDO
Before Insert POSITION 0
AS
  DECLARE VARIABLE MAX_CODIGO INTEGER;
BEGIN
	SELECT COALESCE(MAX(CODIGO), 0) + 1
	FROM ITENS_PEDIDO
	WHERE CODIGO_PEDIDO = NEW.CODIGO_PEDIDO
	INTO MAX_CODIGO;

	NEW.CODIGO = MAX_CODIGO;
END;
